"""empty message

Revision ID: 580d20157a69
Revises: 22445abadc5d
Create Date: 2016-04-23 00:38:18.497322

"""

# revision identifiers, used by Alembic.
revision = '580d20157a69'
down_revision = '22445abadc5d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follows', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    ### end Alembic commands ###
