"""empty message

Revision ID: be32f06a186a
Revises: 61675b1b338b
Create Date: 2016-04-19 23:29:56.552451

"""

# revision identifiers, used by Alembic.
revision = 'be32f06a186a'
down_revision = '61675b1b338b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.TEXT(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
