"""empty message

Revision ID: df9df093dc11
Revises: 4da404bd36e1
Create Date: 2016-04-11 00:16:24.733212

"""

# revision identifiers, used by Alembic.
revision = 'df9df093dc11'
down_revision = '4da404bd36e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
